version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.6.3
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    #network_mode: host
    ports:
      - "9000:9000"
      
volumes:
  portainer_data:
